# Generated by Django 4.1.5 on 2023-02-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='hint',
        ),
    ]
