# Generated by Django 4.1.6 on 2023-02-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_questionmodel_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizname',
            name='image',
            field=models.ImageField(default=1, upload_to='cat_imgs/'),
            preserve_default=False,
        ),
    ]
