# Generated by Django 4.1.7 on 2023-02-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_quizname_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizname',
            name='image',
        ),
    ]
